apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zqte9rc8d-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:3fc325c2bae37d6f78ab332575ecf75fae0560a5@sha256:bb7ff77d173152dcce559b8006dfe29b544ca1af6567bd45ced3e556b07aea22
          name: container-image
