apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zqte9rc8d-go
  janus-idp.io/tekton: zqte9rc8d-go
  backstage.io/kubernetes-id: zqte9rc8d-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zqte9rc8d-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
