apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zqte9rc8d-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zqte9rc8d-go 
  name: zqte9rc8d-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zqte9rc8d-go 
